import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, describe, expect, test, vi } from "vite-plus/test";

import { generate } from "./generate.js";

const sbtcAbi = {
  functions: [],
  variables: [],
  maps: [],
  fungible_tokens: [],
  non_fungible_tokens: [],
};

async function createRoot() {
  return await mkdtemp(join(tmpdir(), "clarity-abitype-"));
}

async function writeConfig(root: string, config: unknown) {
  await writeFile(
    join(root, "clarity.config.mjs"),
    `export default ${JSON.stringify(config)};`,
  );
}

afterEach(() => {
  vi.unstubAllGlobals();
});

describe("generate", () => {
  test("uses inline abi from config", async () => {
    const root = await createRoot();
    const out = join(root, "generated.ts");
    await writeConfig(root, {
      out,
      contracts: [
        {
          abi: sbtcAbi,
          contract: "SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token",
          name: "sbtcToken",
        },
      ],
    });

    await generate({ root });

    const content = await readFile(out, "utf8");
    expect(content).toContain("// Generated by clarity-abitype. Do not edit.");
    expect(content).toContain("export const sbtcTokenAbi = {");
    expect(content).toContain("functions: []");
    expect(content).toContain("} as const;");
  });

  test("fetches abi from the Stacks API", async () => {
    const root = await createRoot();
    const out = join(root, "generated.ts");
    await writeConfig(root, {
      contracts: [
        {
          contract: "SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token",
          name: "sbtcToken",
        },
      ],
      out,
    });
    const fetch = vi.fn(
      async () => new Response(JSON.stringify(sbtcAbi), { status: 200 }),
    );
    vi.stubGlobal("fetch", fetch);

    await generate({ root });

    expect(fetch).toHaveBeenCalledWith(
      "https://api.mainnet.hiro.so/v2/contracts/interface/SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4/sbtc-token",
      { signal: expect.any(AbortSignal) },
    );
    expect(await readFile(out, "utf8")).toContain("export const sbtcTokenAbi");
  });

  test("uses custom api url", async () => {
    const root = await createRoot();
    await writeConfig(root, {
      apiUrl: "https://api.testnet.hiro.so/",
      contracts: [{ contract: "ST1.foo", name: "foo" }],
      out: join(root, "generated.ts"),
    });
    const fetch = vi.fn(
      async () => new Response(JSON.stringify(sbtcAbi), { status: 200 }),
    );
    vi.stubGlobal("fetch", fetch);

    await generate({ root });

    expect(fetch).toHaveBeenCalledWith(
      "https://api.testnet.hiro.so/v2/contracts/interface/ST1/foo",
      { signal: expect.any(AbortSignal) },
    );
  });

  test("sorts contracts by name", async () => {
    const root = await createRoot();
    const out = join(root, "generated.ts");
    await writeConfig(root, {
      out,
      contracts: [
        { abi: sbtcAbi, contract: "SP1.b", name: "beta" },
        { abi: sbtcAbi, contract: "SP1.a", name: "alpha" },
      ],
    });

    await generate({ root });

    const content = await readFile(out, "utf8");
    expect(content.indexOf("export const alphaAbi")).toBeLessThan(
      content.indexOf("export const betaAbi"),
    );
  });

  test("supports config functions", async () => {
    const root = await createRoot();
    const out = join(root, "generated.ts");
    await writeFile(
      join(root, "clarity.config.mjs"),
      `export default () => ({
        out: ${JSON.stringify(out)},
        contracts: [{ abi: ${JSON.stringify(sbtcAbi)}, contract: "SP1.foo", name: "foo" }],
      });`,
    );

    await generate({ root });

    expect(await readFile(out, "utf8")).toContain("export const fooAbi");
  });

  test("removes stale output and warns when no contracts", async () => {
    const root = await createRoot();
    const out = join(root, "generated.ts");
    await writeFile(out, "stale");
    await writeConfig(root, { contracts: [], out });

    await generate({ root });

    await expect(readFile(out, "utf8")).rejects.toThrow("ENOENT");
  });

  test("sanitizes line terminators in banners", async () => {
    const root = await createRoot();
    const out = join(root, "generated.ts");
    await writeConfig(root, {
      out,
      contracts: [
        { abi: sbtcAbi, contract: "SP1.foo\n// evil", name: "foo\nbar" },
      ],
    });

    await generate({ root });

    const content = await readFile(out, "utf8");
    expect(content).toContain("// foo bar\n// SP1.foo // evil\n/");
  });

  test("throws when config is missing", async () => {
    const root = await createRoot();

    await expect(generate({ root })).rejects.toThrow("Config not found");
  });

  test("throws on invalid contract identifier", async () => {
    const root = await createRoot();
    await writeConfig(root, {
      contracts: [{ contract: "invalid", name: "foo" }],
      out: join(root, "generated.ts"),
    });

    await expect(generate({ root })).rejects.toThrow(
      'Invalid contract identifier "invalid"',
    );
  });

  test("throws on duplicate contract names", async () => {
    const root = await createRoot();
    await writeConfig(root, {
      contracts: [
        { abi: sbtcAbi, contract: "SP1.a", name: "foo" },
        { abi: sbtcAbi, contract: "SP1.b", name: "foo" },
      ],
      out: join(root, "generated.ts"),
    });

    await expect(generate({ root })).rejects.toThrow(
      'Contracts "foo" and "foo" generate the same export "fooAbi".',
    );
  });

  test("throws when names derive the same export", async () => {
    const root = await createRoot();
    await writeConfig(root, {
      contracts: [
        { abi: sbtcAbi, contract: "SP1.a", name: "my-token" },
        { abi: sbtcAbi, contract: "SP1.b", name: "my_token" },
      ],
      out: join(root, "generated.ts"),
    });

    await expect(generate({ root })).rejects.toThrow(
      'generate the same export "myTokenAbi"',
    );
  });

  test("throws on failed fetch", async () => {
    const root = await createRoot();
    await writeConfig(root, {
      contracts: [{ contract: "SP1.foo", name: "foo" }],
      out: join(root, "generated.ts"),
    });
    vi.stubGlobal(
      "fetch",
      vi.fn(async () => new Response("Not found", { status: 404 })),
    );

    await expect(generate({ root })).rejects.toThrow(
      'Failed to fetch ABI for "SP1.foo" (404',
    );
  });
});
