name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write # Required for OIDC
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: vite-plus setup
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "24"
          cache: true

      # Update npm to the latest version to ensure compatibility with OIDC and other features
      - run: npm install -g npm@latest

      - name: Build
        run: vp run build

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: vp run version
          publish: vp run release
          commit: "chore: release"
          title: "chore: create new release"
        env:
          # Fix for OIDC https://github.com/actions/setup-node/issues/1440
          NODE_AUTH_TOKEN: ""
          NPM_TOKEN: ""
          NPM_CONFIG_PROVENANCE: true
